### PR TITLE
Idea tag

### PR DESCRIPTION
**Pull request by saghen**
Small pull request for and ideas tag. There may be too many here that would polute the channels. Are there any sites that have ideas that we can link to?

### CODE REVIEW

**Comment by jannes-io** [comment]
(pvtHenk here)
I'd feel like something about https://github.com/public-apis/public-apis would fit in here nicely too.

**Comment by saghen** [comment]
I don't see which API fits in. Any ideas?

**Comment by jannes-io** [comment]
@Saghen,

Just in general "Make a user interface for a public api" or something?

**Comment by saghen** [comment]
Ah gotcha. Yeah I can add that 😛

**Pull request merged**
